apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeport
  labels:
    app: nginx-nodeport
    demo: service
spec:
  containers:
  - name: nginx-nodeport
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-nodeport
    demo: service
  ports:
  - protocol: TCP
    port: 80  # services port
    targetPort: 80   # container port 
