apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    app: nginx-lb
    demo: service
spec:
  containers:
  - name: nginx-lb
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
