apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod  # Pod
metadata:
  name: app
  labels:
    demo: ebs-dynamic
spec:
  containers:
  - name: nginx  
    image: nginx   # Uses official NGINX image from Docker Hub.
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html  # Mounts EBS volume into /usr/share/nginx/html (web root folder).
  nodeSelector:   # Ensures Pod is scheduled on a node in same Availability Zone as EBS volume (e.g., us-east-1d)
   zone: 1d
  volumes:
  - name: nginx-data
    persistentVolumeClaim: # Connects Pod to the PVC (ebs-static).
      claimName: ebs-dynamic
---
apiVersion: v1
kind: Service      #Exposes Pods internally or externally.# services in load balancer
metadata:
  name: ebs-dynamic
spec:
  type: LoadBalancer # Creates an AWS Elastic Load Balancer (ELB) automatically.
  selector:          # Matches Pods with label
    demo: ebs-static
  ports:
  - protocol: TCP
    port: 80        # Service port
    targetPort: 80  # Pod container port                      