apiVersion: v1
kind: Pod
metadata:
  name: labels-demo
  labels:
   course: DevOps
   trainer: kanth
   duration: "120"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
