apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: COURSE
      value: "DevOps"
    - name: TRAINER
      value: "Kanth"
    - name: DURATION
      value: "120"
