apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  
  
  
spec:
  containers:
  - name: hello-world
    image: nginx
    ports:
    - containerPort: 80
    resources:
        requests:           #mrequest means soft link
          cpu: "200m"       # 200 milliCPU (0.2 CPU)
          memory: "256Mi"   # 256 MB RAM
        limits:
          cpu: "500m"       # 0.5 CPU max
          memory: "512Mi"   # 512 MB RAM max