apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  namespace: roboshop
  
spec:
  containers:
  - name: config-pod
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: course
      valueFrom:     # meaning past value
        configMapKeyRef:
          name: devops-config      # ఏ ConfigMap నుంచి తీసుకోవాలి
          key: course          # ఏ key తీసుకోవాలి
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: trainer       
                